In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
size = 10_000_000

# python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end - start} seconds")

# numpy array
np_arr = np.array(py_list)
start = time.time()
# Vectorization
sq_arr = np_arr ** 2
end = time.time()
print(f"Numpy array time = {end - start} seconds")

python list time = 2.225355625152588 seconds
Numpy array time = 0.04238176345825195 seconds


In [4]:
# in term of memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)}bytes")

print(f"python list size = {np_arr.nbytes }bytes")

python list size = 800000560000000bytes
python list size = 80000000bytes


In [5]:
np_arr = np.array([1,2,3,4,5,6])
print(np_arr, type(np_arr), np_arr.dtype, np_arr.shape)

np_arr2 = np.array([1,2,3,4,5,6,"taha"])
print(np_arr2, type(np_arr2), np_arr2.dtype, np_arr2.shape)

arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,22,12]])
print(arr_2d, type(arr_2d), arr_2d.shape, arr_2d.dtype)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' '6' 'taha'] <class 'numpy.ndarray'> <U21 (7,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 22 12]] <class 'numpy.ndarray'> (3, 4) int64


In [6]:
# create array from scratch level or build in methods
arr1 = np.zeros((2,3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((4,3) ) #prefill
print(arr2, arr2.shape)

arr3 = np.full((4,3), 100 ) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye((4 ) ) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange (0,11,3)  #range elements
print(arr5, arr5.shape)

arr6 = np.linspace( 1,100,4 ) #evently space array
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[0 3 6 9] (4,)
[  1.  34.  67. 100.] (4,)


In [7]:
# 06. array properties 
arr = np.array([[1,2,3,4,5], [3,6,5,7,9], [10,9,4,6,3]])
print(arr, arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

arr_float = arr.astype(np.float64)
print(arr_float)

[[ 1  2  3  4  5]
 [ 3  6  5  7  9]
 [10  9  4  6  3]] (3, 5)
int64
15
2
[[ 1.  2.  3.  4.  5.]
 [ 3.  6.  5.  7.  9.]
 [10.  9.  4.  6.  3.]]


In [8]:
# 07. Reshaping array / operations on numpy arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshape = arr.reshape((3,2))
print(reshape, reshape.shape)

flatten = arr.flatten()
print(flatten, flatten.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
# 08. indexing on array
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

arr1 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr1[0][1])

# fancy indexing
idx = [1,2,4]
print(arr[idx])  

# boolean indexing
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

1
4
2
[2 3 5]
[3 4 5]
[2 4]
[1 3 5]


In [10]:
# 09. slicing operations
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [11]:
# 10. copy vs view
arr_list = [1,2,3,4,5,6]
sub_list = arr_list[1:4]
print(sub_list)
sub_list[1] = 900
print(sub_list)
print(arr_list)

print("------------- numpy array---------")
arr = np.array([1,2,3,4,5])
print(arr)
sub_list1 = arr[0:3].copy()
print(sub_list1)
sub_list1[2] = 100
print(sub_list1)
print(arr)

[2, 3, 4]
[2, 900, 4]
[1, 2, 3, 4, 5, 6]
------------- numpy array---------
[1 2 3 4 5]
[1 2 3]
[  1   2 100]
[1 2 3 4 5]


In [12]:
# multi_dimensional arrays
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [13]:
arr3D = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]])  #2 * 3 * 2
print(arr3D, arr3D.shape)

# indexing in 3D array 
print(arr3D[0,1,1])

# silicing in 3D array
print(arr3D[:,0,:])  # first row from both layers
print(arr3D[:,:,0])  # first column from both layers

arr3D[:,0,:]  = 99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [14]:
# vectorization
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,25,25])
print(arr ** 2 )
print(arr % 2 == 0)
print(arr + 5)
print(arr + arr2)

[ 1  4  9 16 25 36]
[False  True False  True False  True]
[ 6  7  8  9 10 11]
[12 14 16 18 30 31]


In [19]:
# Broadcasting
arr = np.array([1,2,3,4,5,6]) # for scaler
print(arr + 5)
arr1 = np.array([1,2,3 ]) # for vector
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1 + arr2)
print(arr1.shape)
print(arr2.shape)


[ 6  7  8  9 10 11]
[[2 4 6]
 [5 7 9]]
(3,)
(2, 3)


In [21]:
# Normilize
arr = np.array([1,2,3,4,5,6])

print(np.mean(arr))
print(np.std(arr))

mean = np.mean(arr) 
std_dev = np.std(arr)

normilized = (arr - mean)/std_dev 
print(normilized)

3.5
1.707825127659933
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [28]:
# Mathematical fnx

# Aggregation
arr = np.array([1,2,3,4,5,6])
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))




3.5
1.707825127659933
21
720
1
6
2.9166666666666665
3.5
0
5


In [31]:
# power fnx
arr = np.array([1,2,3,4,5,6])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 2))


[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 1  4  9 16 25 36]


In [35]:
# log 
arr = np.array([1,2,3,4,5,6])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [41]:
# ronding
print(np.round(3.87))
print(np.round(3.49))
print(np.floor(3.49))
print(np.ceil(3.49))
print(np.trunc(3.49))




4.0
3.0
3.0
4.0
3.0
[1 2 3 4 5 6 7 9]


In [44]:
# extras
arr = np.array([1,2,2,3,4,7,9,3,4,5,6])
print(np.unique(arr))

print(np.sort(arr))

arr = np.array([1,2,-2,3,4,-7,9,-3,4,-5,6])
print(np.abs(arr))
print(np.tan(arr))

[1 2 3 4 5 6 7 9]
[1 2 2 3 3 4 4 5 6 7 9]
[1 2 2 3 4 7 9 3 4 5 6]
[ 1.55740772 -2.18503986  2.18503986 -0.14254654  1.15782128 -0.87144798
 -0.45231566  0.14254654  1.15782128  3.38051501 -0.29100619]
